const Playlist = require('./playList.js');
const db = require('./db.js');

const sampleQueue =[
  [
      "youtube",
      {
          "kind": "youtube#searchResult",
          "etag": "\"XI7nbFXulYBIpL0ayR_gDh3eu1k/gG2D1TheXxrlM9wLPR-LERqQEuk\"",
          "id": {
              "kind": "youtube#video",
              "videoId": "pgN-vvVVxMA"
          },
          "snippet": {
              "publishedAt": "2018-03-02T05:05:53.000Z",
              "channelId": "UCM9r1xn6s30OnlJWb-jc3Sw",
              "title": "XXXTENTACION - SAD!",
              "description": "enjoy. ? HERE: https://xxxtentacion.lnk.to/NEWALBUM.",
              "thumbnails": {
                  "default": {
                      "url": "https://i.ytimg.com/vi/pgN-vvVVxMA/default.jpg",
                      "width": 120,
                      "height": 90
                  },
                  "medium": {
                      "url": "https://i.ytimg.com/vi/pgN-vvVVxMA/mqdefault.jpg",
                      "width": 320,
                      "height": 180
                  },
                  "high": {
                      "url": "https://i.ytimg.com/vi/pgN-vvVVxMA/hqdefault.jpg",
                      "width": 480,
                      "height": 360
                  }
              },
              "channelTitle": "XXXTENTACION",
              "liveBroadcastContent": "none"
          }
      }
  ],
  [
      "spotify",
      {
          "album": {
              "album_type": "album",
              "artists": [
                  {
                      "external_urls": {
                          "spotify": "https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny"
                      },
                      "href": "https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny",
                      "id": "6LuN9FCkKOj5PcnpouEgny",
                      "name": "Khalid",
                      "type": "artist",
                      "uri": "spotify:artist:6LuN9FCkKOj5PcnpouEgny"
                  }
              ],
              "available_markets": [
                  "AD",
                  "AE",
                  "AR",
                  "AT",
                  "AU",
                  "BE",
                  "BG",
                  "BH",
                  "BO",
                  "BR",
                  "CA",
                  "CH",
                  "CL",
                  "CO",
                  "CR",
                  "CY",
                  "CZ",
                  "DE",
                  "DK",
                  "DO",
                  "DZ",
                  "EC",
                  "EE",
                  "EG",
                  "ES",
                  "FI",
                  "FR",
                  "GB",
                  "GR",
                  "GT",
                  "HK",
                  "HN",
                  "HU",
                  "ID",
                  "IE",
                  "IL",
                  "IS",
                  "IT",
                  "JO",
                  "JP",
                  "KW",
                  "LB",
                  "LI",
                  "LT",
                  "LU",
                  "LV",
                  "MA",
                  "MC",
                  "MT",
                  "MX",
                  "MY",
                  "NI",
                  "NL",
                  "NO",
                  "NZ",
                  "OM",
                  "PA",
                  "PE",
                  "PH",
                  "PL",
                  "PS",
                  "PT",
                  "PY",
                  "QA",
                  "RO",
                  "SA",
                  "SE",
                  "SG",
                  "SK",
                  "SV",
                  "TH",
                  "TN",
                  "TR",
                  "TW",
                  "US",
                  "UY",
                  "VN",
                  "ZA"
              ],
              "external_urls": {
                  "spotify": "https://open.spotify.com/album/6kf46HbnYCZzP6rjvQHYzg"
              },
              "href": "https://api.spotify.com/v1/albums/6kf46HbnYCZzP6rjvQHYzg",
              "id": "6kf46HbnYCZzP6rjvQHYzg",
              "images": [
                  {
                      "height": 640,
                      "url": "https://i.scdn.co/image/5026fddc6c0b69e931ae99130f15d4214f1e7d41",
                      "width": 640
                  },
                  {
                      "height": 300,
                      "url": "https://i.scdn.co/image/3f2cc8df9f891830695c00446ce86bd892e60886",
                      "width": 300
                  },
                  {
                      "height": 64,
                      "url": "https://i.scdn.co/image/ee9853bb9b13357f12b691eaeac8b9a44c5c99d8",
                      "width": 64
                  }
              ],
              "name": "American Teen",
              "release_date": "2017-04-27",
              "release_date_precision": "day",
              "total_tracks": 15,
              "type": "album",
              "uri": "spotify:album:6kf46HbnYCZzP6rjvQHYzg"
          },
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/6LuN9FCkKOj5PcnpouEgny"
                  },
                  "href": "https://api.spotify.com/v1/artists/6LuN9FCkKOj5PcnpouEgny",
                  "id": "6LuN9FCkKOj5PcnpouEgny",
                  "name": "Khalid",
                  "type": "artist",
                  "uri": "spotify:artist:6LuN9FCkKOj5PcnpouEgny"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 244746,
          "explicit": false,
          "external_ids": {
              "isrc": "USRC11700145"
          },
          "external_urls": {
              "spotify": "https://open.spotify.com/track/52Qu0no0NBho3zyRmjlsHn"
          },
          "href": "https://api.spotify.com/v1/tracks/52Qu0no0NBho3zyRmjlsHn",
          "id": "52Qu0no0NBho3zyRmjlsHn",
          "is_local": false,
          "name": "Another Sad Love Song",
          "popularity": 74,
          "preview_url": "https://p.scdn.co/mp3-preview/fec7107fea99b85f559ba528322c904e98581dff?cid=67f8f02307f74dafa4d23af41f134d6c",
          "track_number": 4,
          "type": "track",
          "uri": "spotify:track:52Qu0no0NBho3zyRmjlsHn"
      }
  ],
  [
      "spotify",
      {
          "album": {
              "album_type": "single",
              "artists": [
                  {
                      "external_urls": {
                          "spotify": "https://open.spotify.com/artist/71Mm7PHNOerxK5GkaT9ACY"
                      },
                      "href": "https://api.spotify.com/v1/artists/71Mm7PHNOerxK5GkaT9ACY",
                      "id": "71Mm7PHNOerxK5GkaT9ACY",
                      "name": "Jakubi",
                      "type": "artist",
                      "uri": "spotify:artist:71Mm7PHNOerxK5GkaT9ACY"
                  }
              ],
              "available_markets": [
                  "AD",
                  "AE",
                  "AR",
                  "AT",
                  "AU",
                  "BE",
                  "BG",
                  "BH",
                  "BO",
                  "BR",
                  "CA",
                  "CH",
                  "CL",
                  "CO",
                  "CR",
                  "CY",
                  "CZ",
                  "DE",
                  "DK",
                  "DO",
                  "DZ",
                  "EC",
                  "EE",
                  "EG",
                  "ES",
                  "FI",
                  "FR",
                  "GB",
                  "GR",
                  "GT",
                  "HK",
                  "HN",
                  "HU",
                  "ID",
                  "IE",
                  "IL",
                  "IS",
                  "IT",
                  "JO",
                  "JP",
                  "KW",
                  "LB",
                  "LI",
                  "LT",
                  "LU",
                  "LV",
                  "MA",
                  "MC",
                  "MT",
                  "MX",
                  "MY",
                  "NI",
                  "NL",
                  "NO",
                  "NZ",
                  "OM",
                  "PA",
                  "PE",
                  "PH",
                  "PL",
                  "PS",
                  "PT",
                  "PY",
                  "QA",
                  "RO",
                  "SA",
                  "SE",
                  "SG",
                  "SK",
                  "SV",
                  "TH",
                  "TN",
                  "TR",
                  "TW",
                  "US",
                  "UY",
                  "VN",
                  "ZA"
              ],
              "external_urls": {
                  "spotify": "https://open.spotify.com/album/1R5sHnvpPYAWEMHXPDbOuW"
              },
              "href": "https://api.spotify.com/v1/albums/1R5sHnvpPYAWEMHXPDbOuW",
              "id": "1R5sHnvpPYAWEMHXPDbOuW",
              "images": [
                  {
                      "height": 640,
                      "url": "https://i.scdn.co/image/e5360719fc9282bc7e8e32f88b77d524cbf97e54",
                      "width": 640
                  },
                  {
                      "height": 300,
                      "url": "https://i.scdn.co/image/4e5856b04cd176e908da93e5fd3a72ab42f4290f",
                      "width": 300
                  },
                  {
                      "height": 64,
                      "url": "https://i.scdn.co/image/bb3916d44368e18273d5b91bd8c97119ca6b5b40",
                      "width": 64
                  }
              ],
              "name": "Couch Potato",
              "release_date": "2015-04-20",
              "release_date_precision": "day",
              "total_tracks": 1,
              "type": "album",
              "uri": "spotify:album:1R5sHnvpPYAWEMHXPDbOuW"
          },
          "artists": [
              {
                  "external_urls": {
                      "spotify": "https://open.spotify.com/artist/71Mm7PHNOerxK5GkaT9ACY"
                  },
                  "href": "https://api.spotify.com/v1/artists/71Mm7PHNOerxK5GkaT9ACY",
                  "id": "71Mm7PHNOerxK5GkaT9ACY",
                  "name": "Jakubi",
                  "type": "artist",
                  "uri": "spotify:artist:71Mm7PHNOerxK5GkaT9ACY"
              }
          ],
          "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 195188,
          "explicit": false,
          "external_ids": {
              "isrc": "USSM11502230"
          },
          "external_urls": {
              "spotify": "https://open.spotify.com/track/4wFzDwH40XrQL067ETa9wy"
          },
          "href": "https://api.spotify.com/v1/tracks/4wFzDwH40XrQL067ETa9wy",
          "id": "4wFzDwH40XrQL067ETa9wy",
          "is_local": false,
          "name": "Couch Potato",
          "popularity": 47,
          "preview_url": "https://p.scdn.co/mp3-preview/33c4615f97fbaf1491d25fb6e289b86f90fee181?cid=67f8f02307f74dafa4d23af41f134d6c",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:4wFzDwH40XrQL067ETa9wy"
      }
  ]
]

const sampleData = {
  username: 'tony',
  password: 'test',
  playlists: {
    name: 'sample playlist',
    queue: sampleQueue,
  }
}

Playlist.create(sampleData, (err) => {
  console.log('seeded sample data');
});